In [6]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
from Bio import Entrez

In [ ]:
def Needleman_alignment(seq1, seq2, match=1, mismatch=-1, gap=-2):
    n, m = len(seq1), len(seq2)
    
    
    values = np.zeros((n + 1, m + 1), dtype=int)
    aligns = np.zeros((n + 1, m + 1), dtype=str)
    
    
    values[:, 0] = np.array([gap*i for i in range(n+1)])
    values[0, :] = np.array([gap*i for i in range(m+1)])
    aligns[1:, 0] = "↑"
    aligns[0, 1:] = "←"
    
    
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            match_score = values[i - 1, j - 1] + (match if seq1[i - 1] == seq2[j - 1] else mismatch)
            vertucal_score = values[i - 1, j] + gap
            horizontal_score = values[i, j - 1] + gap
            
            values[i, j] = max(match_score, vertucal_score, horizontal_score)
            if values[i, j] == match_score:
                aligns[i, j] = "↖"
            elif values[i, j] == vertucal_score:
                aligns[i, j] = "↑"
            else:
                aligns[i, j] = "←"
    
    
    aligned_seq1, aligned_seq2 = "", ""
    i, j = n, m
    while i > 0 or j > 0:
        print(values[i, j])
        if aligns[i, j] == "↖":
            aligned_seq1 = seq1[i - 1] + aligned_seq1
            aligned_seq2 = seq2[j - 1] + aligned_seq2
            i -= 1
            j -= 1
        elif aligns[i, j] == "↑":
            aligned_seq1 = seq1[i - 1] + aligned_seq1
            aligned_seq2 = "-" + aligned_seq2
            i -= 1
        else:  # "←"
            aligned_seq1 = "-" + aligned_seq1
            aligned_seq2 = seq2[j - 1] + aligned_seq2
            j -= 1
    print(values)
    print(aligns)

    return aligned_seq1, aligned_seq2, values[n, m]

seq1="AGCT"
seq2="ATGCT"

aligned1, aligned2, score = Needleman_alignment(seq1, seq2,mismatch=-1,gap=-2)
print(aligned1)
print(aligned2)
print(score)

2
1
0
-1
1
[[  0  -2  -4  -6  -8 -10]
 [ -2   1  -1  -3  -5  -7]
 [ -4  -1   0   0  -2  -4]
 [ -6  -3  -2  -1   1  -1]
 [ -8  -5  -2  -3  -1   2]]
[['' '←' '←' '←' '←' '←']
 ['↑' '↖' '←' '←' '←' '←']
 ['↑' '↑' '↖' '↖' '←' '←']
 ['↑' '↑' '↖' '↖' '↖' '←']
 ['↑' '↑' '↖' '↖' '↑' '↖']]
A-GCT
ATGCT
2


In [ ]:
def Smith_alignment(seq1, seq2, match=1, mismatch=-1, gap=-2):
    n, m = len(seq1), len(seq2)
    
    
    values = np.zeros((n + 1, m + 1), dtype=int)
    
    
    max_score = 0
    max_pos = (0, 0)
    
    
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            match_score = values[i - 1, j - 1] + (match if seq1[i - 1] == seq2[j - 1] else mismatch)
            vertical_score = values[i - 1, j] + gap
            horizontal_score = values[i, j - 1] + gap
            values[i, j] = max(0, match_score, vertical_score, horizontal_score)  
            
            
            if values[i, j] > max_score:
                max_score = values[i, j]
                max_pos = (i, j)
    
   
    aligned_seq1, aligned_seq2 = "", ""
    i, j = max_pos
    while values[i, j] > 0:
        if values[i, j] == values[i - 1, j - 1] + (match if seq1[i - 1] == seq2[j - 1] else mismatch):
            aligned_seq1 = seq1[i - 1] + aligned_seq1
            aligned_seq2 = seq2[j - 1] + aligned_seq2
            i -= 1
            j -= 1
        elif values[i, j] == values[i - 1, j] + gap:
            aligned_seq1 = seq1[i - 1] + aligned_seq1
            aligned_seq2 = "-" + aligned_seq2
            i -= 1
        else:  # values[i, j] == values[i, j - 1] + gap
            aligned_seq1 = "-" + aligned_seq1
            aligned_seq2 = seq2[j - 1] + aligned_seq2
            j -= 1
    
    return aligned_seq1, aligned_seq2, max_score



seq1 = "AGCT"
seq2 = "ATGCT"
aligned1, aligned2, score = Smith_alignment(seq1, seq2)
print(aligned1)
print(aligned2)
print(score)

GCT
GCT
3
